[package]
name = "ralias"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "3.0.0"
home = "0.5.11"
log = "0.4.26"
regex = "1.11.1"
simple_logger = "5.0.0"
tempfile = "3.2"
